// j9-vikings
export default {
      id: "j9-vikings",
      jornada: "Jornada 9",
      opponent: "Vikings",
      result: "5 - 2",
      date: "04 Mai 2026",
      youtubeId: "I3EZnlW91sE",
      vimeoId: null,
      idealMinutesPerPlayer: 12.0,
      goalkeeperMinutes: { "Ivan Mico": 20.6, "Joan Medina": 3.4 },
      savesManual: { "Ivan Mico": 4, "Joan Medina": 4 },
      shots: {
        "Arnau Sentis": [{ time: "4:40", onTarget: true }, { time: "5:26", onTarget: false }, { time: "17:56", onTarget: false }],
        "Joan Medina":  [{ time: "0:39", onTarget: false }, { time: "4:19", onTarget: true }, { time: "6:36", onTarget: true }, { time: "17:14", onTarget: true }, { time: "33:15", onTarget: true }, { time: "34:49", onTarget: false }],
        "Roger Miro":   [{ time: "7:45", onTarget: true }, { time: "8:07", onTarget: true }, { time: "11:30", onTarget: true }, { time: "12:55", onTarget: false }, { time: "22:00", onTarget: true }],
        "Roi Seoane":   [{ time: "14:45", onTarget: true }, { time: "34:15", onTarget: false }],
        "Chengzhi Li":  [{ time: "10:18", onTarget: false }, { time: "39:25", onTarget: true }],
        "Oriol Tomas":  [{ time: "13:10", onTarget: true }, { time: "31:06", onTarget: false }, { time: "35:25", onTarget: false }],
        "Pau Ibañez":   [{ time: "17:20", onTarget: false }],
        "Ivan Mico":    [{ time: "23:47", onTarget: true }],
      },
      keyPasses: {
        "Roger Miro":   [{ time: "0:39" }, { time: "5:26" }, { time: "28:34" }, { time: "39:25" }],
        "Arnau Sentis": [{ time: "4:19" }, { time: "17:20" }, { time: "23:47" }, { time: "34:49" }],
        "Chengzhi Li":  [{ time: "7:45" }],
        "Pau Ibañez":   [{ time: "8:07" }],
        "Ivan Mico":    [{ time: "17:14" }, { time: "34:08" }],
        "Joan Medina":  [{ time: "34:15" }],
        "Roi Seoane":   [{ time: "34:49" }],
      },
      dribbles: {
        "Chengzhi Li":  [{ time: "10:18" }, { time: "12:40" }, { time: "12:40" }],
        "Oriol Tomas":  [{ time: "13:10" }],
        "Arnau Sentis": [{ time: "15:28" }],
        "Joan Medina":  [{ time: "33:15" }],
      },
      events: {
        substitutions: [
          { time: "0:00",  goalkeeper: "Ivan Mico",   onPitch: ["Roger Miro", "Arnau Sentis", "Pau Ibañez", "Joan Medina"] },
          { time: "7:25",  goalkeeper: "Ivan Mico",   onPitch: ["Roi Seoane", "Chengzhi Li", "Roger Miro", "Pau Ibañez"] },
          { time: "13:30", goalkeeper: "Ivan Mico",   onPitch: ["Arnau Sentis", "Joan Medina", "Roi Seoane", "Oriol Tomas"] },
          { time: "17:30", goalkeeper: "Ivan Mico",   onPitch: ["Pau Ibañez", "Arnau Sentis", "Joan Medina", "Oriol Tomas"] },
          { time: "17:45", goalkeeper: "Ivan Mico",   onPitch: ["Chengzhi Li", "Oriol Tomas", "Pau Ibañez", "Arnau Sentis"] },
          { time: "18:52", goalkeeper: "Ivan Mico",   onPitch: ["Roger Miro", "Chengzhi Li", "Pau Ibañez", "Oriol Tomas"] },
          { time: "20:38", goalkeeper: "Joan Medina", onPitch: ["Roi Seoane", "Pau Ibañez", "Roger Miro", "Ivan Mico"] },
          { time: "22:48", goalkeeper: "Joan Medina", onPitch: ["Arnau Sentis", "Pau Ibañez", "Roger Miro", "Roi Seoane"] },
          { time: "24:51", goalkeeper: "Joan Medina", onPitch: ["Oriol Tomas", "Roi Seoane", "Roger Miro", "Arnau Sentis"] },
          { time: "25:51", goalkeeper: "Joan Medina", onPitch: ["Chengzhi Li", "Oriol Tomas", "Arnau Sentis", "Pau Ibañez"] },
          { time: "28:15", goalkeeper: "Joan Medina", onPitch: ["Roger Miro", "Pau Ibañez", "Chengzhi Li", "Oriol Tomas"] },
          { time: "30:44", goalkeeper: "Ivan Mico",   onPitch: ["Roi Seoane", "Oriol Tomas", "Joan Medina", "Roger Miro"] },
          { time: "33:05", goalkeeper: "Ivan Mico",   onPitch: ["Arnau Sentis", "Joan Medina", "Roi Seoane", "Oriol Tomas"] },
          { time: "36:39", goalkeeper: "Ivan Mico",   onPitch: ["Pau Ibañez", "Chengzhi Li", "Roger Miro", "Arnau Sentis"] },
          { time: "39:40", goalkeeper: "",            onPitch: [] },
        ],
        cards: [
          { time: "26:42", color: "yellow", player: "Chengzhi Li" },
        ],
        goals: [
          { time: "4:40", type: "favor", scorer: "Arnau Sentis", assist: "Joan Medina", goalkeeper: "Ivan Mico",
            zone: "C6", shotPos: { x: 773, y: 220 }, assistPos: { x: 738, y: 201 }, conductPos: null, goalPos: { x: 252, y: 169 },
            onPitch: ["Roger Miro","Arnau Sentis","Pau Ibañez","Joan Medina"], notes: "Corner de Pau, cap de Medina que queia a porteria, Sentis la remata." },
          { time: "6:36", type: "favor", scorer: "Joan Medina", assist: "Roger Miro", goalkeeper: "Ivan Mico",
            zone: "B6", shotPos: { x: 721, y: 209 }, assistPos: { x: 713, y: 284 }, conductPos: null, goalPos: { x: 15, y: 191 },
            onPitch: ["Roger Miro","Arnau Sentis","Pau Ibañez","Joan Medina"], notes: "Miro verticalitza i assisteix Medina. Xut fluix que el rival no gosa tocar i entra sol." },
          { time: "11:05", type: "contra", goalkeeper: "Ivan Mico", onPitch: ["Roi Seoane","Chengzhi Li","Roger Miro","Pau Ibañez"], notes: "Falta directa des de la vora de l'area." },
          { time: "11:30", type: "favor", scorer: "Roger Miro", assist: null, goalkeeper: "Ivan Mico",
            zone: "C6", shotPos: { x: 698, y: 211 }, assistPos: { x: 328, y: 213 }, conductPos: { x: 582, y: 261 }, goalPos: { x: 150, y: 194 },
            onPitch: ["Roi Seoane","Chengzhi Li","Roger Miro","Pau Ibañez"], notes: "Chengzhi tira llarg a Miro, Roi fa pantalla i el porter no veu el xut li pasa entre les cames pero que dolent." },
          { time: "14:45", type: "favor", scorer: "Roi Seoane", assist: null, goalkeeper: "Ivan Mico",
            zone: "B6", shotPos: { x: 719, y: 199 }, assistPos: { x: 700, y: 222 }, conductPos: null, goalPos: { x: 46, y: 72 },
            onPitch: ["Arnau Sentis","Joan Medina","Roi Seoane","Oriol Tomas"], notes: "Ivan llanca la contra, Medina regata i quan el bloquejen deixa la pilota de punta al Roi. Gol magic." },
          { time: "16:16", type: "contra", goalkeeper: "Ivan Mico", onPitch: ["Arnau Sentis","Joan Medina","Roi Seoane","Oriol Tomas"], notes: "Oriol no desallotja un fora de banda i dos rivals l'empenten dintre." },
          { time: "22:00", type: "favor", scorer: "Roger Miro", assist: "Ivan Mico", goalkeeper: "Joan Medina",
            zone: "D6", shotPos: { x: 698, y: 311 }, assistPos: { x: 632, y: 211 }, conductPos: null, goalPos: { x: 44, y: 179 },
            onPitch: ["Roi Seoane","Pau Ibañez","Roger Miro","Ivan Mico"], notes: "Medina des de porteria filtra a Ivan que assisteix Miro. Gol de fora de l'area." },
          { time: "32:39", type: "contra", goalkeeper: "Ivan Mico", onPitch: ["Roger Miro","Joan Medina","Roi Seoane","Oriol Tomas"], notes: "La perden en defensa intentant sortir en els peus sha de vigilar." },
        ],
        retransmissio: [
          {
            time: "0:25", type: "bona",
            text: "Primera accio i ja hi ha futbol: paret Medina-Miro per la banda, centre a l'area... que ningu remata. Bones idees, execucio per millorar.",
            players: ["Joan Medina", "Roger Miro"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "1:00", type: "bona",
            text: "LA NOS-TRA DE-FEN-SA FUN-CIO-NA. Avui hi ha dies que la defensa funciona i cal celebrar-ho amb la mateixa energia que un gol.",
            players: [], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "1:25", type: "tactica",
            text: "Paret interior Sentis-Miro que prometia molt, pero l'Arnau la tira massa llarga. Spoiler: no sera l'ultima vegada que algú tira 'una mica' massa llarg avui.",
            players: ["Arnau Sentis", "Roger Miro"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "5:26", type: "dolenta",
            text: "Miro fa una passada potent a l'area, la pilota arriba als peus de Sentis amb porteria buida... i li passa per les cames. De manera ridicula. Les cames ho sabien, l'Arnau no.",
            players: ["Arnau Sentis"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "5:50", type: "bona",
            text: "Medina perd el control i, com el cavaller que es, deixa sortir la pilota per fairplay. El rival ho aprofita. L'honradesa es bonica pero cara.",
            players: ["Joan Medina"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "7:15", type: "bona",
            text: "El rival ens fa una paret i deixa un home sol davant porteria. Ivan s'allarga com un gat i para amb PAREDÓN exemplar. Tranquils, tenim porter.",
            players: ["Ivan Mico"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "7:45", type: "dolenta",
            text: "Chengzhi fa una passada de banda a banda perfecta a Miro que xuta clar a porteria... i el Roi li treu el gol de sota els pals. El Roi defensava la seva porteria. A la seva manera.",
            players: ["Chengzhi Li", "Roger Miro", "Roi Seoane"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "12:40", type: "bona",
            text: "Chengzhi es recupera i ens regala dos regats magics que tant estimem. Algú hauria de gravar-los i posar-los en un museu del futbol sala.",
            players: ["Chengzhi Li"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "13:48", type: "bona",
            text: "El rival es queda sol davant porteria. El capita Sentis apareix del no-res, es tira a terra i evita el gol. Accions que no surten al marcador pero que valen com un gol d'or.",
            players: ["Arnau Sentis"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "14:00", type: "dolenta",
            text: "Presentem el pitjor corner defensat de la historia del futbol sala: Oriol d'esquenes que acaba planxat a terra, uns segons de joc completament aturat, i el Roi defensant el corner des del mig del camp. Una obra mestra del caos.",
            players: ["Oriol Tomas", "Roi Seoane"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "16:16", type: "dolenta",
            text: "Oriol dormit en el moment clau. La pilota li cau als peus, ja se li fa tard, no la desallotja i dos rivals l'empenten dintre. Gol en contra. S'accepten excuses per escrit.",
            players: ["Oriol Tomas"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "18:17", type: "dolenta",
            text: "Sentis i Chengzhi combinen de meravella, la passen a Oriol que la controla malament, s'enreda amb la pilota i acaba com un bacalla a la xarxa. Mai millor dit.",
            players: ["Oriol Tomas", "Arnau Sentis", "Chengzhi Li"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "18:40", type: "bona",
            text: "El rival regata al Pau, xuta sol i... PAL. La sort tambe es treballa. O almenys aixi ho veurem des d'avui.",
            players: ["Pau Ibañez"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "22:00", type: "bona",
            text: "40 segons tocant la pilota, Medina des de porteria avanca el joc, filtra a Ivan, Ivan assisteix Miro a l'altra banda: GOL de fora de l'area. Futbol de debò, nois.",
            players: ["Joan Medina", "Ivan Mico", "Roger Miro"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "23:59", type: "bona",
            text: "El rival intenta una contra per l'espai i el Roi intercepta l'accio amb un sacrifici brutal. Les estadistiques no ho recolliran. Nosaltres si.",
            players: ["Roi Seoane"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "25:28", type: "bona",
            text: "Medina para una pilota que no tocava que fos: sortida a temps, puny ferm i tranquil·litat absoluta. El porter amb els punys de gel.",
            players: ["Joan Medina"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "26:42", type: "dolenta",
            text: "El rival decideix que la millor defensa es pegar-li una patada descomunal al Chengzhi. Groga per a ells, falta a prop de l'area. El tir acaba picant a la barrera. Chengzhi se'n riu des del terra.",
            players: ["Chengzhi Li"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "28:05", type: "dolenta",
            text: "Sentis agafa la pilota, mira, pensa, i decideix que l'ha de controlar un altre. El resultat: ni l'un ni l'altre. La pilota ho agraeix marxant sola.",
            players: ["Arnau Sentis"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "28:34", type: "dolenta",
            text: "Contra a la Viking: Miro fa una passada de cirugia i l'Oriol el segueix. Davant porteria, amb un gol claríssim a davant, l'Oriol decideix que avui no. L'Oriol nomes sap marcar gols extraordinaris. Cap altre.",
            players: ["Roger Miro", "Oriol Tomas"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "28:44", type: "tactica",
            text: "Aclarim el dubte del minut anterior: eren mans. El que semblava una oportunitat era, de fet, un gest involuntari d'algú que no vol la pilota per les bones.",
            players: [], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "30:04", type: "dolenta",
            text: "El rival ha decidit que el Chengzhi es la seva diana personal. A la que pot, li dona. L'arbitre mira cap a un altre costat. Chengzhi segueix jugant i somrient.",
            players: ["Chengzhi Li"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "31:06", type: "bona",
            text: "Altra patada al nostre equip, l'arbitre per fi xiula. L'Oriol xuta per l'esquadra exterior. No entra, pero l'estetica era innegable.",
            players: ["Oriol Tomas"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "33:15", type: "bona",
            text: "Medina, en mode Neymar, regata un rival a la frontal i remata a porta. El porter rival para el xut. No entra, pero el bancal ho ha vist tot.",
            players: ["Joan Medina"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "33:45", type: "dolenta",
            text: "El porter rival, en la seva crisi existencial, llanca la pilota directament a l'esquena del Sentis. Maniobra que no surt a cap manual pero que s'emporta el premi a l'antiesportiva de la jornada.",
            players: ["Arnau Sentis"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "34:03", type: "bona",
            text: "Sentis, sota pressio, regala la pilota. Ivan surt disparat com un llamp i salva la jugada. El gol no entra. El cor si que ha sortit.",
            players: ["Arnau Sentis", "Ivan Mico"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "34:08", type: "bona",
            text: "Ivan llanca una pilota llarga al Roi que genera perill real. El Roi no acaba de disparar pero el missatge era clar: avui juguem a contraatac.",
            players: ["Ivan Mico", "Roi Seoane"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "34:15", type: "dolenta",
            text: "Medina fa una passada quirurgica a la frontal per al Roi. El que passa a continuacio es el pitjor xut que s'ha vist en un pavello de futbol sala. El Roi ho sap. Tots ho sabem.",
            players: ["Joan Medina", "Roi Seoane"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "34:39", type: "bona",
            text: "Ivan para una pilota que havia de ser gol. Sortida valenta, cos posat i fora de perill.",
            players: ["Ivan Mico"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "32:39", type: "dolenta",
            text: "Ivan havia sortit i la porteria estava buida. El rival no ho desaprofita i marca des de fora de l'area. Penalitzats per intentar jugar en curt.",
            players: ["Ivan Mico"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "34:49", type: "bona",
            text: "Ivan impulsa una pilota alta, Sentis sense deixar-la botar la pica directa al cap del Roi. El Roi la deixa caure a la frontal i Medina, sense que boti, fa una volea increible... que surt fora. Increible de principi a fi. Fins i tot el final.",
            players: ["Ivan Mico", "Arnau Sentis", "Roi Seoane", "Joan Medina"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "35:05", type: "dolenta",
            text: "L'arbitre amones ta el rival amb targeta blava al del banquillo pel comentari 'arbitre mi puta madre pita mejor'. Bravo al rival per la creativitat.",
            players: [], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "35:25", type: "bona",
            text: "Oriol s'inventa una jugada individual per la banda, regata, xuta... i el xut supera la porteria per poc. El porter no s'esperava res i la pilota tampoc acaba entrant.",
            players: ["Oriol Tomas"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "35:55", type: "bona",
            text: "El rival fa un saque de banda que ens agafa desprevinguts. Xuta rasa amb Ivan fora de la porteria. Sort que hi ha Sentis per parar el xut i Ivan agafa la pilota rapid. El cor: un altre cop al terra.",
            players: ["Arnau Sentis", "Ivan Mico"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "38:00", type: "bona",
            text: "PAREDÓN d'Ivan per enviar una pilota a corner que semblava gol des de la graderia. 2 minuts per al final. Podem guanyar.",
            players: ["Ivan Mico"], videoUrl: null, photo: null, photoHover: null,
          },
          {
            time: "39:25", type: "bona",
            text: "Sentis intercepta al limit, el Miro roba la pilota i el camp s'obre: 3 contra 1. Chengzhi xuta a porta i despres sona el xiulet final. PRIMERA VICTORIA DE LA REAL TIESADA DE LA HISTORIA. Enhorabona a tots, nois.",
            players: ["Arnau Sentis", "Roger Miro", "Chengzhi Li"], videoUrl: null, photo: null, photoHover: null,
          },
        ],
      }
    };
