// =============================================
// SPLIT 1 — Futbol 8 — Temporada 2024-25
// =============================================

export const DATABASE_S1 = {
  teamName: "Real Tiesada",
  season: "2024-25",
  sport: "Futbol 8",

  // Plantilla — mateixos jugadors que el split actual, adaptats
  roster: [
    { name: "Aron",   shirtName: "ARON",   position: "Migcampista", photo: "players/arnau.png",  photoCel: "players/arnau_cel.png" },
    { name: "Sentis", shirtName: "SENTIS", position: "Migcampista", photo: "players/arnau.png",  photoCel: "players/arnau_cel.png" },
    { name: "Miro",   shirtName: "MIRÓ",   position: "Davanter",    photo: "players/roger.png",  photoCel: "players/roger_cel.png" },
    { name: "Oriol",  shirtName: "ORIOL",  position: "Migcampista", photo: "players/oriol.png",  photoCel: "players/oriol_cel.png" },
    { name: "Medina", shirtName: "MEDINA", position: "Porter",      photo: null,                 photoCel: null },
    { name: "Coro",   shirtName: "CORO",   position: "Davanter",    photo: null,                 photoCel: null },
    { name: "Lluc",   shirtName: "LLUC",   position: "Defensa",     photo: null,                 photoCel: null },
    { name: "Marc",   shirtName: "MARC",   position: "Migcampista", photo: null,                 photoCel: null },
    { name: "Pau",    shirtName: "PAU",    position: "Porter",      photo: null,                 photoCel: null },
    { name: "Roi",    shirtName: "ROI",    position: "Defensa",     photo: "players/roger.png",  photoCel: null },
  ],

  matches: [
    {
      id: "s1-j1",
      jornada: "Jornada 1",
      opponent: "Real Magic Balompié",
      date: "2024",
      result: "3-?",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 0, jugadesBones: 7,  cagades: 1, golsEncaixats: 0, golsFavor: 2,  golsContra: 7,  parades: 0, pts: 6.5  },
        "Coro":   { gols: 0, assists: 1, jugadesBones: 2,  cagades: 1, golsEncaixats: 1, golsFavor: 1,  golsContra: 3,  parades: 0, pts: 4.25 },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 7,  cagades: 2, golsEncaixats: 3, golsFavor: 1,  golsContra: 5,  parades: 3, pts: 4.5  },
        "Marc":   { gols: 0, assists: 0, jugadesBones: 3,  cagades: 2, golsEncaixats: 0, golsFavor: 1,  golsContra: 3,  parades: 0, pts: 1.5  },
        "Medina": { gols: 1, assists: 0, jugadesBones: 1,  cagades: 4, golsEncaixats: 4, golsFavor: 3,  golsContra: 8,  parades: 9, pts: 5.25 },
        "Miro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Oriol":  { gols: 1, assists: 0, jugadesBones: 3,  cagades: 0, golsEncaixats: 0, golsFavor: 2,  golsContra: 4,  parades: 0, pts: 10   },
        "Pau":    { gols: 1, assists: 1, jugadesBones: 2,  cagades: 1, golsEncaixats: 1, golsFavor: 3,  golsContra: 6,  parades: 1, pts: 12   },
        "Roi":    { gols: 0, assists: 0, jugadesBones: 0,  cagades: 2, golsEncaixats: 0, golsFavor: 0,  golsContra: 4,  parades: 0, pts: -4   },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 4,  cagades: 1, golsEncaixats: 0, golsFavor: 2,  golsContra: 5,  parades: 0, pts: 4.5  },
      },
      mvpVotes: { "Pau": 3, "Coro": 2, "Oriol": 1 },
      mvpWinner: "Pau",
    },
    {
      id: "s1-j2",
      jornada: "Jornada 2",
      opponent: "Aston Birra",
      date: "2024",
      result: "2-11",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 1, jugadesBones: 5,  cagades: 2, golsEncaixats: 0, golsFavor: 2,  golsContra: 9,  parades: 0, pts: 5.5  },
        "Coro":   { gols: 1, assists: 0, jugadesBones: 4,  cagades: 0, golsEncaixats: 3, golsFavor: 1,  golsContra: 7,  parades: 2, pts: 7.25 },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 4,  cagades: 0, golsEncaixats: 0, golsFavor: 1,  golsContra: 1,  parades: 0, pts: 5.5  },
        "Marc":   { gols: 1, assists: 0, jugadesBones: 5,  cagades: 0, golsEncaixats: 0, golsFavor: 1,  golsContra: 7,  parades: 0, pts: 8.5  },
        "Medina": { gols: 0, assists: 0, jugadesBones: 2,  cagades: 3, golsEncaixats: 5, golsFavor: 2,  golsContra: 9,  parades: 7, pts: -1   },
        "Miro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Oriol":  { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Pau":    { gols: 0, assists: 0, jugadesBones: 1,  cagades: 1, golsEncaixats: 2, golsFavor: 1,  golsContra: 8,  parades: 6, pts: -1   },
        "Roi":    { gols: 0, assists: 0, jugadesBones: 0,  cagades: 1, golsEncaixats: 1, golsFavor: 1,  golsContra: 7,  parades: 0, pts: -2.75},
        "Sentis": { gols: 0, assists: 1, jugadesBones: 7,  cagades: 0, golsEncaixats: 0, golsFavor: 1,  golsContra: 7,  parades: 0, pts: 8.5  },
      },
      mvpVotes: { "Coro": 3, "Marc": 2, "Aron": 1 },
      mvpWinner: "Coro",
    },
    {
      id: "s1-j3",
      jornada: "Jornada 3",
      opponent: "Inafuma y Beben",
      date: "2024",
      result: "3-7",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Coro":   { gols: 1, assists: 0, jugadesBones: 4,  cagades: 0, golsEncaixats: 0, golsFavor: 2,  golsContra: 2,  parades: 0, pts: 12   },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 1,  cagades: 2, golsEncaixats: 0, golsFavor: 2,  golsContra: 6,  parades: 0, pts: 0    },
        "Marc":   { gols: 0, assists: 0, jugadesBones: 6,  cagades: 1, golsEncaixats: 0, golsFavor: 2,  golsContra: 4,  parades: 0, pts: 7    },
        "Medina": { gols: 0, assists: 0, jugadesBones: 1,  cagades: 0, golsEncaixats: 5, golsFavor: 1,  golsContra: 5,  parades: 8, pts: 1.25 },
        "Miro":   { gols: 1, assists: 1, jugadesBones: 1,  cagades: 2, golsEncaixats: 0, golsFavor: 3,  golsContra: 4,  parades: 0, pts: 11   },
        "Oriol":  { gols: 0, assists: 0, jugadesBones: 0,  cagades: 1, golsEncaixats: 0, golsFavor: 0,  golsContra: 3,  parades: 0, pts: -2.5 },
        "Pau":    { gols: 0, assists: 1, jugadesBones: 0,  cagades: 0, golsEncaixats: 2, golsFavor: 3,  golsContra: 4,  parades: 4, pts: 7.5  },
        "Roi":    { gols: 1, assists: 0, jugadesBones: 0,  cagades: 1, golsEncaixats: 0, golsFavor: 2,  golsContra: 5,  parades: 0, pts: 5.5  },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 2,  parades: 0, pts: -1   },
      },
      mvpVotes: { "Coro": 3, "Miro": 2, "Roi": 1 },
      mvpWinner: "Coro",
    },
    {
      id: "s1-j4",
      jornada: "Jornada 4",
      opponent: "Pink Devils",
      date: "2024",
      result: "3-9",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Coro":   { gols: 1, assists: 0, jugadesBones: 4,  cagades: 0, golsEncaixats: 0, golsFavor: 3,  golsContra: 7,  parades: 0, pts: 11.5 },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Marc":   { gols: 0, assists: 0, jugadesBones: 4,  cagades: 1, golsEncaixats: 0, golsFavor: 1,  golsContra: 7,  parades: 0, pts: 1.5  },
        "Medina": { gols: 0, assists: 1, jugadesBones: 1,  cagades: 1, golsEncaixats: 5, golsFavor: 2,  golsContra: 8,  parades: 4, pts: 2.75 },
        "Miro":   { gols: 0, assists: 1, jugadesBones: 4,  cagades: 0, golsEncaixats: 0, golsFavor: 2,  golsContra: 8,  parades: 0, pts: 7    },
        "Oriol":  { gols: 1, assists: 0, jugadesBones: 0,  cagades: 2, golsEncaixats: 0, golsFavor: 3,  golsContra: 6,  parades: 0, pts: 6    },
        "Pau":    { gols: 1, assists: 0, jugadesBones: 3,  cagades: 1, golsEncaixats: 4, golsFavor: 3,  golsContra: 8,  parades: 11, pts: 10.75},
        "Roi":    { gols: 0, assists: 0, jugadesBones: 0,  cagades: 1, golsEncaixats: 0, golsFavor: 1,  golsContra: 1,  parades: 0, pts: 0.5  },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
      },
      mvpVotes: { "Marc": 3, "Pau": 2, "Medina": 1 },
      mvpWinner: "Marc",
    },
    {
      id: "s1-j5",
      jornada: "Jornada 5",
      opponent: "Birra Real",
      date: "2024",
      result: "2-10",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 0, jugadesBones: 2,  cagades: 0, golsEncaixats: 0, golsFavor: 1,  golsContra: 8,  parades: 0, pts: 0    },
        "Coro":   { gols: 2, assists: 0, jugadesBones: 7,  cagades: 0, golsEncaixats: 1, golsFavor: 2,  golsContra: 7,  parades: 9, pts: 19.5 },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Marc":   { gols: 0, assists: 0, jugadesBones: 7,  cagades: 1, golsEncaixats: 2, golsFavor: 1,  golsContra: 9,  parades: 2, pts: 3.5  },
        "Medina": { gols: 0, assists: 0, jugadesBones: 2,  cagades: 1, golsEncaixats: 3, golsFavor: 2,  golsContra: 6,  parades: 5, pts: 2.5  },
        "Miro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Oriol":  { gols: 0, assists: 1, jugadesBones: 2,  cagades: 2, golsEncaixats: 0, golsFavor: 1,  golsContra: 5,  parades: 0, pts: 2.5  },
        "Pau":    { gols: 0, assists: 0, jugadesBones: 3,  cagades: 1, golsEncaixats: 4, golsFavor: 1,  golsContra: 9,  parades: 1, pts: -1.25},
        "Roi":    { gols: 0, assists: 0, jugadesBones: 1,  cagades: 1, golsEncaixats: 0, golsFavor: 2,  golsContra: 6,  parades: 0, pts: 1    },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
      },
      mvpVotes: { "Coro": 3, "Marc": 2, "Medina": 1 },
      mvpWinner: "Coro",
    },
    {
      id: "s1-j6",
      jornada: "Jornada 6",
      opponent: "Vodka Juniors",
      date: "2024",
      result: "0-4",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 0, jugadesBones: 5,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 3,  parades: 0, pts: 3.5  },
        "Coro":   { gols: 0, assists: 0, jugadesBones: 9,  cagades: 3, golsEncaixats: 1, golsFavor: 0,  golsContra: 3,  parades: 3, pts: 5    },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 7,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 3,  parades: 0, pts: 5.5  },
        "Marc":   { gols: 0, assists: 0, jugadesBones: 1,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 2,  parades: 0, pts: 0    },
        "Medina": { gols: 0, assists: 0, jugadesBones: 7,  cagades: 0, golsEncaixats: 3, golsFavor: 0,  golsContra: 4,  parades: 4, pts: 5.25 },
        "Miro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Oriol":  { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Pau":    { gols: 0, assists: 0, jugadesBones: 7,  cagades: 1, golsEncaixats: 0, golsFavor: 0,  golsContra: 2,  parades: 2, pts: 5.5  },
        "Roi":    { gols: 0, assists: 0, jugadesBones: 1,  cagades: 1, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
      },
      mvpVotes: { "Marc": 3, "Pau": 2, "Lluc": 0 },
      mvpWinner: "Marc",
    },
    {
      id: "s1-j7",
      jornada: "Jornada 7",
      opponent: "Fig Frames",
      date: "2024",
      result: "1-3",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 0, assists: 0, jugadesBones: 12, cagades: 0, golsEncaixats: 0, golsFavor: 1,  golsContra: 2,  parades: 0, pts: 13   },
        "Coro":   { gols: 0, assists: 0, jugadesBones: 7,  cagades: 0, golsEncaixats: 1, golsFavor: 1,  golsContra: 2,  parades: 2, pts: 8.25 },
        "Lluc":   { gols: 0, assists: 0, jugadesBones: 4,  cagades: 0, golsEncaixats: 1, golsFavor: 0,  golsContra: 3,  parades: 4, pts: 3.25 },
        "Marc":   { gols: 1, assists: 0, jugadesBones: 9,  cagades: 1, golsEncaixats: 0, golsFavor: 1,  golsContra: 2,  parades: 1, pts: 14.25},
        "Medina": { gols: 0, assists: 0, jugadesBones: 6,  cagades: 0, golsEncaixats: 0, golsFavor: 1,  golsContra: 1,  parades: 4, pts: 8.5  },
        "Miro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Oriol":  { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Pau":    { gols: 0, assists: 0, jugadesBones: 2,  cagades: 1, golsEncaixats: 1, golsFavor: 1,  golsContra: 3,  parades: 0, pts: 1.25 },
        "Roi":    { gols: 0, assists: 0, jugadesBones: 1,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 1,  parades: 0, pts: 0.5  },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
      },
      mvpVotes: { "Aron": 3, "Lluc": 3, "Marc": 1 },
      mvpWinner: "Aron",
    },
    {
      id: "s1-j8",
      jornada: "Jornada 8",
      opponent: "Racing de Saberbeber",
      date: "2024",
      result: "?-?",
      youtubeId: null,
      vimeoId: null,
      playerStats: {
        "Aron":   { gols: 2, assists: 0, jugadesBones: 3,  cagades: 1, golsEncaixats: 1, golsFavor: 5,  golsContra: 8,  parades: 8, pts: 19.75},
        "Coro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Lluc":   { gols: 3, assists: 0, jugadesBones: 8,  cagades: 1, golsEncaixats: 1, golsFavor: 5,  golsContra: 8,  parades: 1, pts: 28   },
        "Marc":   { gols: 0, assists: 1, jugadesBones: 7,  cagades: 0, golsEncaixats: 1, golsFavor: 5,  golsContra: 7,  parades: 5, pts: 17.5 },
        "Medina": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Miro":   { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
        "Oriol":  { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 1,  parades: 0, pts: -0.5 },
        "Pau":    { gols: 0, assists: 1, jugadesBones: 4,  cagades: 0, golsEncaixats: 5, golsFavor: 3,  golsContra: 8,  parades: 10, pts: 10.25},
        "Roi":    { gols: 0, assists: 1, jugadesBones: 1,  cagades: 0, golsEncaixats: 1, golsFavor: 3,  golsContra: 6,  parades: 2, pts: 7.25 },
        "Sentis": { gols: 0, assists: 0, jugadesBones: 0,  cagades: 0, golsEncaixats: 0, golsFavor: 0,  golsContra: 0,  parades: 0, pts: 0    },
      },
      mvpVotes: { "Lluc": 3, "Aron": 2, "Marc": 1 },
      mvpWinner: "Lluc",
    },
  ],
};
